### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by aleurcelay** [UBC-MDS/DSCI_532_Suicide_Statistics#4]
-You have a broken link to your submission in two README files. 
-The app users are not clearly defined in the overview section, did you mean people working with mental health organizations instead of mental health initiatives? Also, the last part where you describe what kind of information and visuals will users will get is a bit vague.
-The scenario section is very well done 👍 
-Are your sliders intended for selecting ranges or single values? The age slider looks like a range one, but it should be a single value I think.
-No sketch of the subpage when selecting a single country provided.
-The bottom right icons in the sketch are the opposite of what you said in the description section (The world icon is not in the home page).

**Comment by RayceRossum** [comment]
- Will remove placeholder README.md, these were used to add folders for structure
- Mental Health Initiatives is correct. 
- Our sliders will select range. We would like to be able to select age ranges as well. We may adapt this to checkboxes.
- Fixed image link
- We'll likely just include our plots on the main page instead of on subpages but we will worry about that at a later time.
